spring:
  datasource:
    url: jdbc:postgresql://electricity-billing-db.cxcg228yy6a8.ap-south-1.rds.amazonaws.com:5432/ebm_db
    username: postgres
    password: pvsEbmDb24$
    driver-class-name: org.postgresql.Driver

server:
  port: 8082
